// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OauthService.proto

package grpc.search.oauth.o.grpc.model;

public interface OauthRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.OauthRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
