// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OauthService.proto

package grpc.search.oauth.o.grpc.model;

public interface OauthReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.OauthReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 messagecode = 1;</code>
   */
  int getMessagecode();

  /**
   * <code>string token = 2;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 2;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
