// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OauthService.proto

package grpc.search.oauth.o.grpc.model;

public final class OauthServerProto {
  private OauthServerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_OauthRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_OauthRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_OauthReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_OauthReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022OauthService.proto\022\nhelloworld\".\n\014Oaut" +
      "hRequest\022\014\n\004name\030\001 \001(\t\022\020\n\010password\030\002 \001(\t" +
      "\"0\n\nOauthReply\022\023\n\013messagecode\030\001 \001(\005\022\r\n\005t" +
      "oken\030\002 \001(\t2T\n\rGetOauthToken\022C\n\rgetOauthT" +
      "oken\022\030.helloworld.OauthRequest\032\026.hellowo" +
      "rld.OauthReply\"\000B5\n\031grpc.search.server.g" +
      "rpc.oB\020OauthServerProtoP\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_helloworld_OauthRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_OauthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_OauthRequest_descriptor,
        new java.lang.String[] { "Name", "Password", });
    internal_static_helloworld_OauthReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloworld_OauthReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_OauthReply_descriptor,
        new java.lang.String[] { "Messagecode", "Token", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
