// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SqlDataService.proto

package grpc.search.service.grpc;

public interface SqlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.SqlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string token = 2;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 2;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string sql = 3;</code>
   */
  java.lang.String getSql();
  /**
   * <code>string sql = 3;</code>
   */
  com.google.protobuf.ByteString
      getSqlBytes();
}
