// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiscoveryService.proto

package grpc.search.discovery.d.grpc;

public final class DiscoveryServerProto {
  private DiscoveryServerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_DiscoveryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_DiscoveryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_DiscoveryReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_DiscoveryReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_RegisterReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_RegisterReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026DiscoveryService.proto\022\nhelloworld\"6\n\020" +
      "DiscoveryRequest\022\020\n\010username\030\001 \001(\t\022\020\n\010pa" +
      "ssword\030\002 \001(\t\"<\n\016DiscoveryReply\022\023\n\013messag" +
      "ecode\030\001 \001(\005\022\025\n\rdiscoveryInfo\030\002 \001(\t\"\036\n\017Re" +
      "gisterRequest\022\013\n\003url\030\002 \001(\t\"$\n\rRegisterRe" +
      "ply\022\023\n\013messagecode\030\001 \001(\0052^\n\014GetDiscovery" +
      "\022N\n\020getDiscoveryInfo\022\034.helloworld.Discov" +
      "eryRequest\032\032.helloworld.DiscoveryReply\"\000" +
      "2i\n\025RegisterDiscoveryInfo\022P\n\024registerDis" +
      "coverInfo\022\033.helloworld.RegisterRequest\032\031" +
      ".helloworld.RegisterReply\"\000B9\n\031grpc.sear" +
      "ch.server.grpc.dB\024DiscoveryServerProtoP\001" +
      "\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_helloworld_DiscoveryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_DiscoveryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_DiscoveryRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_helloworld_DiscoveryReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloworld_DiscoveryReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_DiscoveryReply_descriptor,
        new java.lang.String[] { "Messagecode", "DiscoveryInfo", });
    internal_static_helloworld_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_helloworld_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_RegisterRequest_descriptor,
        new java.lang.String[] { "Url", });
    internal_static_helloworld_RegisterReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_helloworld_RegisterReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_RegisterReply_descriptor,
        new java.lang.String[] { "Messagecode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
