// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiscoveryService.proto

package grpc.search.discovery.d.grpc;

public interface DiscoveryReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.DiscoveryReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 messagecode = 1;</code>
   */
  int getMessagecode();

  /**
   * <code>string discoveryInfo = 2;</code>
   */
  java.lang.String getDiscoveryInfo();
  /**
   * <code>string discoveryInfo = 2;</code>
   */
  com.google.protobuf.ByteString
      getDiscoveryInfoBytes();
}
