// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiscoveryService.proto

package grpc.search.discovery.d.grpc;

/**
 * <pre>
 * The response message containing the greetings
 * </pre>
 *
 * Protobuf type {@code helloworld.DiscoveryReply}
 */
public  final class DiscoveryReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:helloworld.DiscoveryReply)
    DiscoveryReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DiscoveryReply.newBuilder() to construct.
  private DiscoveryReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DiscoveryReply() {
    messagecode_ = 0;
    discoveryInfo_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DiscoveryReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            messagecode_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            discoveryInfo_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DiscoveryServerProto.internal_static_helloworld_DiscoveryReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DiscoveryServerProto.internal_static_helloworld_DiscoveryReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DiscoveryReply.class, DiscoveryReply.Builder.class);
  }

  public static final int MESSAGECODE_FIELD_NUMBER = 1;
  private int messagecode_;
  /**
   * <code>int32 messagecode = 1;</code>
   */
  public int getMessagecode() {
    return messagecode_;
  }

  public static final int DISCOVERYINFO_FIELD_NUMBER = 2;
  private volatile java.lang.Object discoveryInfo_;
  /**
   * <code>string discoveryInfo = 2;</code>
   */
  public java.lang.String getDiscoveryInfo() {
    java.lang.Object ref = discoveryInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      discoveryInfo_ = s;
      return s;
    }
  }
  /**
   * <code>string discoveryInfo = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDiscoveryInfoBytes() {
    java.lang.Object ref = discoveryInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      discoveryInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messagecode_ != 0) {
      output.writeInt32(1, messagecode_);
    }
    if (!getDiscoveryInfoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, discoveryInfo_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messagecode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, messagecode_);
    }
    if (!getDiscoveryInfoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, discoveryInfo_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof DiscoveryReply)) {
      return super.equals(obj);
    }
    DiscoveryReply other = (DiscoveryReply) obj;

    boolean result = true;
    result = result && (getMessagecode()
        == other.getMessagecode());
    result = result && getDiscoveryInfo()
        .equals(other.getDiscoveryInfo());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGECODE_FIELD_NUMBER;
    hash = (53 * hash) + getMessagecode();
    hash = (37 * hash) + DISCOVERYINFO_FIELD_NUMBER;
    hash = (53 * hash) + getDiscoveryInfo().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DiscoveryReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DiscoveryReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DiscoveryReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DiscoveryReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DiscoveryReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DiscoveryReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DiscoveryReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DiscoveryReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static DiscoveryReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static DiscoveryReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static DiscoveryReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DiscoveryReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(DiscoveryReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The response message containing the greetings
   * </pre>
   *
   * Protobuf type {@code helloworld.DiscoveryReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helloworld.DiscoveryReply)
          DiscoveryReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DiscoveryServerProto.internal_static_helloworld_DiscoveryReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DiscoveryServerProto.internal_static_helloworld_DiscoveryReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DiscoveryReply.class, DiscoveryReply.Builder.class);
    }

    // Construct using DiscoveryReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      messagecode_ = 0;

      discoveryInfo_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DiscoveryServerProto.internal_static_helloworld_DiscoveryReply_descriptor;
    }

    @java.lang.Override
    public DiscoveryReply getDefaultInstanceForType() {
      return DiscoveryReply.getDefaultInstance();
    }

    @java.lang.Override
    public DiscoveryReply build() {
      DiscoveryReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public DiscoveryReply buildPartial() {
      DiscoveryReply result = new DiscoveryReply(this);
      result.messagecode_ = messagecode_;
      result.discoveryInfo_ = discoveryInfo_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DiscoveryReply) {
        return mergeFrom((DiscoveryReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DiscoveryReply other) {
      if (other == DiscoveryReply.getDefaultInstance()) return this;
      if (other.getMessagecode() != 0) {
        setMessagecode(other.getMessagecode());
      }
      if (!other.getDiscoveryInfo().isEmpty()) {
        discoveryInfo_ = other.discoveryInfo_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      DiscoveryReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (DiscoveryReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int messagecode_ ;
    /**
     * <code>int32 messagecode = 1;</code>
     */
    public int getMessagecode() {
      return messagecode_;
    }
    /**
     * <code>int32 messagecode = 1;</code>
     */
    public Builder setMessagecode(int value) {
      
      messagecode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 messagecode = 1;</code>
     */
    public Builder clearMessagecode() {
      
      messagecode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object discoveryInfo_ = "";
    /**
     * <code>string discoveryInfo = 2;</code>
     */
    public java.lang.String getDiscoveryInfo() {
      java.lang.Object ref = discoveryInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        discoveryInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string discoveryInfo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDiscoveryInfoBytes() {
      java.lang.Object ref = discoveryInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        discoveryInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string discoveryInfo = 2;</code>
     */
    public Builder setDiscoveryInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      discoveryInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string discoveryInfo = 2;</code>
     */
    public Builder clearDiscoveryInfo() {
      
      discoveryInfo_ = getDefaultInstance().getDiscoveryInfo();
      onChanged();
      return this;
    }
    /**
     * <code>string discoveryInfo = 2;</code>
     */
    public Builder setDiscoveryInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      discoveryInfo_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:helloworld.DiscoveryReply)
  }

  // @@protoc_insertion_point(class_scope:helloworld.DiscoveryReply)
  private static final DiscoveryReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DiscoveryReply();
  }

  public static DiscoveryReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DiscoveryReply>
      PARSER = new com.google.protobuf.AbstractParser<DiscoveryReply>() {
    @java.lang.Override
    public DiscoveryReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DiscoveryReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DiscoveryReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DiscoveryReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public DiscoveryReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

