// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiscoveryService.proto

package grpc.search.discovery.d.grpc;

public interface RegisterReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.RegisterReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 messagecode = 1;</code>
   */
  int getMessagecode();
}
