// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DiscoveryService.proto

package grpc.search.discovery.d.grpc;

public interface RegisterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.RegisterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string url = 2;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 2;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
